version: "3"
services:
  cc-mongo:
    image: "mongo:latest"
    ports:
      - '27017:27017'
    volumes:
      - 'cc-mongo:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
volumes:
  cc-mongo: